before_script:
  - npm install
  - npm install bower
  - bower install
  - gem install compass sass-css-importer --pre
  - sudo apt-get update -qq
  - sudo apt-get install php5 php5-cgi php5-json -qq
script:
  - grunt test
